'use client';

/**
 * Operator-driven locomotives page.
 *
 * Replaces the old "Fleet Health" overview that aggregated 1700
 * autogenerated locomotives. With the new game-like model the
 * operator hand-builds a small fleet, and this page is the place to
 * see / create / delete entries in it.
 *
 * For each row "Открыть" jumps to the existing live DashboardPage
 * (which now also hosts the per-locomotive simulation control panel).
 */

import { useState } from 'react';
import { useRouter } from 'next/navigation';
import {
    ActionIcon,
    Badge,
    Button,
    Card,
    Center,
    Group,
    Loader,
    Stack,
    Table,
    Text,
    Title,
    Tooltip,
} from '@mantine/core';
import {
    IconPlus,
    IconTrain,
    IconExternalLink,
    IconTrash,
    IconBolt,
    IconAlertTriangle,
    IconCheck,
} from '@tabler/icons-react';
import {
    useDeleteSimulatedLocomotiveMutation,
    useGetSimulatedLocomotivesQuery,
    type LocomotiveScenario,
    type SimulatedLocomotive,
} from '@/features/simulator';
import { useLocomotive } from '@/widgets/layout/LocomotiveContext';
import { CreateLocomotiveModal } from './CreateLocomotiveModal';

const SCENARIO_LABEL: Record<LocomotiveScenario, string> = {
    normal: 'Норма',
    degradation: 'Деградация',
    emergency: 'Авария',
};

const SCENARIO_COLOR: Record<LocomotiveScenario, string> = {
    normal: 'teal',
    degradation: 'yellow',
    emergency: 'red',
};

const SCENARIO_ICON: Record<LocomotiveScenario, React.ReactNode> = {
    normal: <IconCheck size={12} />,
    degradation: <IconAlertTriangle size={12} />,
    emergency: <IconBolt size={12} />,
};

export function FleetPage() {
    const router = useRouter();
    const { setLocomotive } = useLocomotive();
    const { data, isLoading, isFetching, refetch } = useGetSimulatedLocomotivesQuery(undefined, {
        pollingInterval: 5000,
    });
    const [deleteSim, { isLoading: deleting }] = useDeleteSimulatedLocomotiveMutation();
    const [modalOpen, setModalOpen] = useState(false);

    const locomotives = data ?? [];

    const handleOpen = (loco: SimulatedLocomotive) => {
        setLocomotive(loco.id, loco.name || loco.id.slice(0, 8));
        router.push('/dashboard');
    };

    const handleDelete = async (loco: SimulatedLocomotive) => {
        // Cheap confirm — modal would be overkill for a pet project.
        if (!confirm(`Удалить ${loco.name || loco.id.slice(0, 8)}?`)) return;
        try {
            await deleteSim(loco.id).unwrap();
        } catch (e) {
            alert(`Не удалось удалить: ${(e as Error).message}`);
        }
    };

    return (
        <Stack gap="md" p="md">
            <Group justify="space-between">
                <Group gap="sm">
                    <IconTrain size={24} />
                    <Title order={3}>Локомотивы</Title>
                    <Badge variant="light" size="lg">
                        {locomotives.length}
                    </Badge>
                    {isFetching && !isLoading && <Loader size="xs" />}
                </Group>
                <Button leftSection={<IconPlus size={16} />} onClick={() => setModalOpen(true)}>
                    Создать локомотив
                </Button>
            </Group>

            <Card withBorder padding="lg" radius="md">
                {isLoading ? (
                    <Center py="xl">
                        <Loader />
                    </Center>
                ) : locomotives.length === 0 ? (
                    <Center py="xl">
                        <Stack align="center" gap="xs">
                            <Text c="dimmed">Симулятор пуст</Text>
                            <Text size="sm" c="dimmed">
                                Нажмите «Создать локомотив», чтобы добавить первый поезд
                            </Text>
                        </Stack>
                    </Center>
                ) : (
                    <Table striped highlightOnHover verticalSpacing="sm">
                        <Table.Thead>
                            <Table.Tr>
                                <Table.Th>Название</Table.Th>
                                <Table.Th>Модель</Table.Th>
                                <Table.Th>Маршрут</Table.Th>
                                <Table.Th>Прогресс</Table.Th>
                                <Table.Th>Скорость</Table.Th>
                                <Table.Th>Режим</Table.Th>
                                <Table.Th>Сценарий</Table.Th>
                                <Table.Th />
                            </Table.Tr>
                        </Table.Thead>
                        <Table.Tbody>
                            {locomotives.map((loco) => (
                                <Table.Tr
                                    key={loco.id}
                                    style={{ cursor: 'pointer' }}
                                    onClick={() => handleOpen(loco)}
                                >
                                    <Table.Td>
                                        <Text fw={500}>{loco.name || '—'}</Text>
                                        <Text size="xs" c="dimmed" ff="monospace">
                                            {loco.id.slice(0, 8)}
                                        </Text>
                                    </Table.Td>
                                    <Table.Td>
                                        <Badge variant="light" size="sm">
                                            {loco.loco_type}
                                        </Badge>
                                    </Table.Td>
                                    <Table.Td>
                                        <Text size="sm">{loco.route_name}</Text>
                                        <Text size="xs" c="dimmed">
                                            {loco.start_km.toFixed(0)} → {loco.end_km.toFixed(0)} км
                                        </Text>
                                    </Table.Td>
                                    <Table.Td>
                                        <Text size="sm">
                                            {(loco.segment_progress * 100).toFixed(1)}%
                                        </Text>
                                        <Text size="xs" c="dimmed">
                                            {loco.distance_km.toFixed(1)} км
                                        </Text>
                                    </Table.Td>
                                    <Table.Td>
                                        <Text size="sm">{loco.speed_kmh.toFixed(0)} км/ч</Text>
                                    </Table.Td>
                                    <Table.Td>
                                        <Badge variant="default" size="sm">
                                            {loco.mode}
                                        </Badge>
                                    </Table.Td>
                                    <Table.Td>
                                        <Badge
                                            variant="light"
                                            color={SCENARIO_COLOR[loco.scenario]}
                                            leftSection={SCENARIO_ICON[loco.scenario]}
                                            size="sm"
                                        >
                                            {SCENARIO_LABEL[loco.scenario]}
                                        </Badge>
                                    </Table.Td>
                                    <Table.Td>
                                        <Group gap={4} justify="flex-end" wrap="nowrap">
                                            <Tooltip label="Открыть в кабине">
                                                <ActionIcon
                                                    variant="subtle"
                                                    onClick={(e) => {
                                                        e.stopPropagation();
                                                        handleOpen(loco);
                                                    }}
                                                >
                                                    <IconExternalLink size={16} />
                                                </ActionIcon>
                                            </Tooltip>
                                            <Tooltip label="Удалить">
                                                <ActionIcon
                                                    variant="subtle"
                                                    color="red"
                                                    loading={deleting}
                                                    onClick={(e) => {
                                                        e.stopPropagation();
                                                        handleDelete(loco);
                                                    }}
                                                >
                                                    <IconTrash size={16} />
                                                </ActionIcon>
                                            </Tooltip>
                                        </Group>
                                    </Table.Td>
                                </Table.Tr>
                            ))}
                        </Table.Tbody>
                    </Table>
                )}
            </Card>

            <CreateLocomotiveModal
                opened={modalOpen}
                onClose={() => setModalOpen(false)}
                onCreated={() => refetch()}
            />
        </Stack>
    );
}
