"""initial timescaledb schema

Revision ID: 5c42cb1eeecd
Revises: 
Create Date: 2026-04-06 02:45:26.694407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5c42cb1eeecd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('locomotive_id', sa.UUID(), nullable=False),
    sa.Column('locomotive_type', sa.Text(), nullable=False),
    sa.Column('sensor_type', sa.Text(), nullable=False),
    sa.Column('severity', sa.Text(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('threshold_min', sa.Float(), nullable=False),
    sa.Column('threshold_max', sa.Float(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('recommendation', sa.Text(), server_default='', nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('acknowledged', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_events_locomotive_id'), 'alert_events', ['locomotive_id'], unique=False)
    op.create_index(op.f('ix_alert_events_timestamp'), 'alert_events', ['timestamp'], unique=False)
    op.create_table('health_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('locomotive_id', sa.UUID(), nullable=False),
    sa.Column('locomotive_type', sa.Text(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('top_factors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('damage_penalty', sa.Float(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_health_snapshots_calculated_at'), 'health_snapshots', ['calculated_at'], unique=False)
    op.create_index(op.f('ix_health_snapshots_locomotive_id'), 'health_snapshots', ['locomotive_id'], unique=False)
    op.create_table('raw_telemetry',
    sa.Column('time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('locomotive_id', sa.UUID(), nullable=False),
    sa.Column('locomotive_type', sa.Text(), nullable=False),
    sa.Column('sensor_type', sa.Text(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('filtered_value', sa.Float(), nullable=False),
    sa.Column('unit', sa.Text(), nullable=False),
    sa.Column('sample_rate_hz', sa.Float(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('time', 'locomotive_id', 'sensor_type')
    )
    # ### end Alembic commands ###

    # --- TimescaleDB-specific DDL ---

    # Convert raw_telemetry to a hypertable with 1-hour chunks.
    op.execute(
        "SELECT create_hypertable('raw_telemetry', 'time', "
        "chunk_time_interval => INTERVAL '1 hour', "
        "if_not_exists => TRUE, migrate_data => TRUE)"
    )

    # Compression: segment by locomotive + sensor, order by time DESC.
    op.execute(
        "ALTER TABLE raw_telemetry SET ("
        "  timescaledb.compress,"
        "  timescaledb.compress_segmentby = 'locomotive_id, sensor_type',"
        "  timescaledb.compress_orderby = 'time DESC'"
        ")"
    )
    op.execute(
        "SELECT add_compression_policy('raw_telemetry', "
        "INTERVAL '1 hours', if_not_exists => TRUE)"
    )

    # Retention: drop raw telemetry older than 72 hours.
    op.execute(
        "SELECT add_retention_policy('raw_telemetry', "
        "INTERVAL '72 hours', if_not_exists => TRUE)"
    )

    # --- Continuous Aggregates ---
    # Three materialized views collapse raw_telemetry into progressively
    # coarser resolutions (1 min, 15 min, 1 hour).
    _aggregates = [
        ("telemetry_1min",  "1 minute",  "10 minutes",  "30 seconds", "30 seconds"),
        ("telemetry_15min", "15 minutes", "1 hour",      "1 minute",   "5 minutes"),
        ("telemetry_1hour", "1 hour",     "3 hours",     "5 minutes",  "15 minutes"),
    ]
    for view, bucket, start_off, end_off, schedule in _aggregates:
        op.execute(f"""
            CREATE MATERIALIZED VIEW {view}
            WITH (timescaledb.continuous) AS
            SELECT
                time_bucket('{bucket}', time) AS bucket,
                locomotive_id,
                locomotive_type,
                sensor_type,
                avg(value)                    AS avg_value,
                min(value)                    AS min_value,
                max(value)                    AS max_value,
                last(value, time)             AS last_value,
                last(filtered_value, time)    AS last_filtered_value,
                max(unit)                     AS unit,
                last(latitude, time)          AS latitude,
                last(longitude, time)         AS longitude
            FROM raw_telemetry
            GROUP BY bucket, locomotive_id, locomotive_type, sensor_type
            WITH NO DATA
        """)
        op.execute(f"""
            SELECT add_continuous_aggregate_policy('{view}',
                start_offset      => INTERVAL '{start_off}',
                end_offset        => INTERVAL '{end_off}',
                schedule_interval => INTERVAL '{schedule}',
                if_not_exists     => TRUE
            )
        """)


def downgrade() -> None:
    """Downgrade schema."""
    # --- Drop continuous aggregates first (they depend on raw_telemetry) ---
    for view in ("telemetry_1hour", "telemetry_15min", "telemetry_1min"):
        op.execute(f"DROP MATERIALIZED VIEW IF EXISTS {view} CASCADE")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('raw_telemetry')
    op.drop_index(op.f('ix_health_snapshots_locomotive_id'), table_name='health_snapshots')
    op.drop_index(op.f('ix_health_snapshots_calculated_at'), table_name='health_snapshots')
    op.drop_table('health_snapshots')
    op.drop_index(op.f('ix_alert_events_timestamp'), table_name='alert_events')
    op.drop_index(op.f('ix_alert_events_locomotive_id'), table_name='alert_events')
    op.drop_table('alert_events')
    # ### end Alembic commands ###
