global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "api-gateway"
    static_configs:
      - targets: ["api-gateway:8000"]

  - job_name: "processor"
    static_configs:
      - targets: ["processor:8001"]

  - job_name: "report-service"
    static_configs:
      - targets: ["report-service:8002"]

  - job_name: "db-writer"
    static_configs:
      - targets: ["db-writer:8004"]

  - job_name: "ws-server"
    static_configs:
      - targets: ["ws-server:8010"]

  - job_name: "analytics-service"
    static_configs:
      - targets: ["analytics-service:8020"]
