"""Route geometry — synthetic polylines + stations for the simulator/UI.

This module is the canonical source of truth for railway routes in the
Locomotive Digital Twin. Both the simulator (which advances locomotive
positions) and the API gateway (which serves /routes to the dashboard)
import the same ``ROUTES`` constant, so they always agree on geometry.

WHY THIS EXISTS
---------------
The original code stored each route as just a (start, end) pair and
linearly interpolated locomotive positions along a great-circle line.
Visually that meant trains slid in straight diagonals across Kazakhstan,
ignoring real terrain and looking obviously fake.

Real railway data (OSM ``railway=rail`` polylines) is the right answer,
but that's a separate iteration — see ``ROADMAP.md``. In the meantime,
this module generates **synthetic but believable** polylines: for each
route we deterministically build ~14 waypoints by walking from start to
end and adding small perpendicular jitter at each step. Result: lines
that bend, curve, and look hand-drawn instead of ruler-straight, with no
external dependencies and no network calls.

Stations are sprinkled along the polyline at evenly spaced kilometre
positions and named after their cumulative distance from start, mimicking
the Soviet/KTZ "Разъезд X км" naming convention. They're synthetic too —
real station names will land in the same future iteration as real OSM
geometry.

The whole module is **deterministic**: for a given route name we always
produce the exact same polyline and station list. That's important
because the simulator and gateway both compute it independently and
must agree.
"""

from __future__ import annotations

import hashlib
import json
import math
import random
import re
from dataclasses import dataclass, field
from itertools import pairwise
from pathlib import Path

# Mean earth radius in metres — good enough for the haversine formula at
# the scale of intra-country railway lines.
_EARTH_RADIUS_M = 6_371_000.0


# Where the OSM-imported route GeoJSON files live (one per route).
# Generated by ``tools/import_osm_railways.py`` against a Geofabrik
# Kazakhstan PBF; ``__post_init__`` reads them at module-import time
# so the simulator and api-gateway pick up real KTZ geometry without
# any runtime download.
#
# Resolution is forgiving: we look in several candidate locations and
# use the first one that exists. The "natural" repo layout finds the
# files via the module's filesystem path, but inside Docker images
# the ``shared`` package is installed as a wheel under .venv/, which
# breaks that walk; we then fall back to the repo-style location
# rooted at /app, the current working directory, or an explicit
# ``KTZ_ROUTES_DIR`` env var. The first hit wins.
def _find_geojson_dir() -> Path:
    import os

    candidates: list[Path] = []
    env = os.environ.get("KTZ_ROUTES_DIR")
    if env:
        candidates.append(Path(env))
    here = Path(__file__).resolve()
    # Repo install: .../shared/shared/route_geometry.py → repo/shared/data/routes
    candidates.append(here.parent.parent.parent / "shared" / "data" / "routes")
    # Wheel install: .venv/lib/.../shared/route_geometry.py → image's /app/shared/data/routes
    candidates.append(Path("/app/shared/data/routes"))
    # CWD-relative fallback for ad-hoc scripts.
    candidates.append(Path.cwd() / "shared" / "data" / "routes")

    for c in candidates:
        if c.is_dir():
            return c
    # Last-resort fallback — return the first candidate so the
    # downstream `is_file()` check returns False cleanly without
    # blowing up on import.
    return candidates[0]


_GEOJSON_DIR = _find_geojson_dir()


# -- Geometry primitives --------------------------------------------------


def haversine_m(lat1: float, lon1: float, lat2: float, lon2: float) -> float:
    """Great-circle distance between two (lat, lon) points, in metres."""
    phi1 = math.radians(lat1)
    phi2 = math.radians(lat2)
    dphi = math.radians(lat2 - lat1)
    dlambda = math.radians(lon2 - lon1)
    a = math.sin(dphi / 2) ** 2 + math.cos(phi1) * math.cos(phi2) * math.sin(dlambda / 2) ** 2
    return 2 * _EARTH_RADIUS_M * math.asin(math.sqrt(a))


def bearing_deg(lat1: float, lon1: float, lat2: float, lon2: float) -> float:
    """Initial compass bearing from p1 to p2 in degrees (0 = N, 90 = E)."""
    phi1 = math.radians(lat1)
    phi2 = math.radians(lat2)
    dlambda = math.radians(lon2 - lon1)
    x = math.sin(dlambda) * math.cos(phi2)
    y = math.cos(phi1) * math.sin(phi2) - math.sin(phi1) * math.cos(phi2) * math.cos(dlambda)
    return (math.degrees(math.atan2(x, y)) + 360) % 360


# -- Synthetic polyline generator -----------------------------------------


def _seeded_rng(name: str) -> random.Random:
    """Per-route RNG so the polyline is deterministic across processes.

    Python's built-in ``hash()`` is randomised per interpreter process
    (PYTHONHASHSEED defaults to random), which means two services
    importing this module would each generate slightly *different*
    synthetic polylines for the same route name — and the operator
    would create a locomotive in service A only to have service B
    reject the chosen station because it lives at a different km.

    Use a stable digest (md5 first 4 bytes) so every process agrees.
    Cryptographic strength irrelevant here; we just need stability.
    """
    digest = hashlib.md5(name.encode("utf-8"), usedforsecurity=False).digest()
    seed = int.from_bytes(digest[:4], "big")
    return random.Random(seed)  # noqa: S311


def generate_polyline(
    name: str,
    lat_start: float,
    lon_start: float,
    lat_end: float,
    lon_end: float,
    *,
    n_segments: int = 14,
    jitter_deg: float = 0.35,
) -> list[tuple[float, float]]:
    """Build a believable hand-drawn-looking railway polyline.

    We walk from start to end in ``n_segments`` equal steps along the
    straight line and at every interior waypoint we shift the position by
    a small random offset perpendicular to the route's main bearing. The
    perpendicular shift is what gives the line its "curving around
    obstacles" feel — without it the random offsets would just be noise
    around the same straight line.

    A second smoothing pass averages each interior point with its
    immediate neighbours so the line bends gently instead of zig-zagging.

    Returns at least ``n_segments + 1`` points; the first equals
    ``(lat_start, lon_start)`` and the last equals ``(lat_end, lon_end)``.
    """
    rng = _seeded_rng(name)

    # Direction of travel as a unit vector in lat/lon space (good enough
    # at this scale; we don't need a true tangent on the ellipsoid).
    dlat = lat_end - lat_start
    dlon = lon_end - lon_start
    length = math.hypot(dlat, dlon)
    if length == 0:
        return [(lat_start, lon_start), (lat_end, lon_end)]

    # Perpendicular unit vector (rotate 90°).
    perp_lat = -dlon / length
    perp_lon = dlat / length

    points: list[tuple[float, float]] = []
    for i in range(n_segments + 1):
        t = i / n_segments
        base_lat = lat_start + dlat * t
        base_lon = lon_start + dlon * t
        if 0 < i < n_segments:
            # Bell-shaped jitter envelope: offsets are larger in the
            # middle of the route than near the endpoints (where the
            # actual railway has to land on the city anyway).
            envelope = math.sin(math.pi * t)
            offset = rng.uniform(-jitter_deg, jitter_deg) * envelope
            base_lat += perp_lat * offset
            base_lon += perp_lon * offset
        points.append((base_lat, base_lon))

    # Two-pass neighbour smoothing on interior points so the polyline
    # transitions are gentle, not piecewise-jagged.
    for _ in range(2):
        smoothed = [points[0]]
        for i in range(1, len(points) - 1):
            a = points[i - 1]
            b = points[i]
            c = points[i + 1]
            smoothed.append(
                (
                    (a[0] + 2 * b[0] + c[0]) / 4,
                    (a[1] + 2 * b[1] + c[1]) / 4,
                )
            )
        smoothed.append(points[-1])
        points = smoothed

    return points


def cumulative_distances(points: list[tuple[float, float]]) -> list[float]:
    """Prefix-sum of segment lengths in metres. ``cum[i]`` is the distance
    from ``points[0]`` to ``points[i]``. Always returns one entry per point;
    ``cum[0] == 0`` and ``cum[-1]`` is the total polyline length."""
    cum = [0.0]
    for (lat1, lon1), (lat2, lon2) in pairwise(points):
        cum.append(cum[-1] + haversine_m(lat1, lon1, lat2, lon2))
    return cum


def position_at_distance(
    points: list[tuple[float, float]],
    cum: list[float],
    distance_m: float,
) -> tuple[float, float, float]:
    """Locate (lat, lon, bearing_deg) on the polyline at the given
    cumulative distance from the first point.

    Distances outside ``[0, cum[-1]]`` are clamped to the endpoints.
    Bearing is computed from the local segment containing the point so
    the train icon can be rotated/oriented if desired.
    """
    if not points:
        return 0.0, 0.0, 0.0
    if distance_m <= 0:
        b = bearing_deg(points[0][0], points[0][1], points[1][0], points[1][1]) if len(points) > 1 else 0.0
        return points[0][0], points[0][1], b
    total = cum[-1]
    if distance_m >= total:
        b = bearing_deg(points[-2][0], points[-2][1], points[-1][0], points[-1][1]) if len(points) > 1 else 0.0
        return points[-1][0], points[-1][1], b

    # Linear scan is fine — polylines have ~16 points. Replace with
    # bisect.bisect_right(cum, distance_m) - 1 if this ever gets hot.
    for i in range(1, len(cum)):
        if cum[i] >= distance_m:
            seg_start = cum[i - 1]
            seg_len = cum[i] - seg_start
            t = (distance_m - seg_start) / seg_len if seg_len > 0 else 0.0
            lat1, lon1 = points[i - 1]
            lat2, lon2 = points[i]
            return (
                lat1 + (lat2 - lat1) * t,
                lon1 + (lon2 - lon1) * t,
                bearing_deg(lat1, lon1, lat2, lon2),
            )

    return points[-1][0], points[-1][1], 0.0


# -- Stations -------------------------------------------------------------


@dataclass(frozen=True)
class Station:
    name: str
    lat: float
    lon: float
    km_from_start: float


def generate_stations(
    name: str,
    points: list[tuple[float, float]],
    cum: list[float],
    *,
    target_count: int = 6,
) -> list[Station]:
    """Place ``target_count`` synthetic stations along the polyline.

    Stations are evenly spaced by cumulative distance (so they don't all
    bunch up at one end of the route) and named after their km-post,
    matching the Soviet/KTZ "Разъезд X км" naming convention. The first
    and last points of the route are skipped (they're the city termini)
    and a small random offset shifts each station slightly off the
    perfect grid so it doesn't look mechanical.
    """
    if target_count <= 0 or len(points) < 2:
        return []
    rng = _seeded_rng(f"{name}::stations")
    total_m = cum[-1]
    if total_m <= 0:
        return []
    spacing_m = total_m / (target_count + 1)

    stations: list[Station] = []
    for i in range(1, target_count + 1):
        nominal = i * spacing_m
        # Random shift up to ±20% of the spacing so stations don't sit
        # at perfect 1/N marks.
        shift = rng.uniform(-spacing_m * 0.2, spacing_m * 0.2)
        d = max(0.0, min(total_m, nominal + shift))
        lat, lon, _ = position_at_distance(points, cum, d)
        km = round(d / 1000.0)
        stations.append(
            Station(
                name=f"Разъезд {km} км",
                lat=lat,
                lon=lon,
                km_from_start=d / 1000.0,
            )
        )
    return stations


# -- GeoJSON loader -------------------------------------------------------


def _slugify(name: str) -> str:
    """Mirror of ``tools/import_osm_railways.py``'s slugify so the lookup
    finds the matching geojson file by route name."""
    return re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-")


def _load_geojson_route(
    name: str,
) -> tuple[list[tuple[float, float]], list[Station]] | None:
    """Try to load real KTZ geometry for ``name`` from the committed
    GeoJSON file.

    Returns ``(waypoints, stations)`` on success, or ``None`` if the
    file isn't there (in which case the caller falls back to the
    synthetic generator). The GeoJSON files are produced by
    ``tools/import_osm_railways.py`` and live under
    ``shared/data/routes/``.
    """
    path = _GEOJSON_DIR / f"{_slugify(name)}.geojson"
    if not path.is_file():
        return None
    try:
        feature = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None

    geometry = feature.get("geometry", {})
    if geometry.get("type") != "LineString":
        return None
    coords = geometry.get("coordinates") or []
    # GeoJSON uses [lon, lat]; we keep the in-process convention as
    # (lat, lon) for everything else, so swap on the way in.
    waypoints: list[tuple[float, float]] = [(float(lat), float(lon)) for lon, lat in coords]
    if len(waypoints) < 2:
        return None

    props = feature.get("properties", {}) or {}
    stations: list[Station] = []
    for s in props.get("stations") or []:
        try:
            stations.append(
                Station(
                    name=str(s["name"]),
                    lat=float(s["lat"]),
                    lon=float(s["lon"]),
                    km_from_start=float(s["km_from_start"]),
                )
            )
        except (KeyError, TypeError, ValueError):
            continue

    return waypoints, stations


# -- Route ----------------------------------------------------------------


@dataclass
class Route:
    """Canonical Route record. ``waypoints``, ``stations`` and
    ``length_m`` are computed once in ``__post_init__`` from the
    start/end pair so callers only have to specify the four numbers."""

    name: str
    lat_start: float
    lon_start: float
    lat_end: float
    lon_end: float
    electrified: bool

    waypoints: list[tuple[float, float]] = field(default_factory=list)
    cum_distances_m: list[float] = field(default_factory=list)
    stations: list[Station] = field(default_factory=list)
    length_m: float = 0.0

    def __post_init__(self) -> None:
        # Resolution order:
        #   1) caller passed waypoints (tests, hand-built routes) — trust them
        #   2) real OSM-imported geometry from shared/data/routes/<slug>.geojson
        #   3) deterministic synthetic polyline (offline / first run / no PBF)
        if not self.waypoints:
            geo = _load_geojson_route(self.name)
            if geo is not None:
                self.waypoints, geo_stations = geo
                # Stations come from the same file unless the caller
                # explicitly supplied their own. Real OSM names beat
                # the synthetic "Разъезд X км" placeholders.
                if not self.stations and geo_stations:
                    self.stations = geo_stations
            else:
                self.waypoints = generate_polyline(
                    self.name,
                    self.lat_start,
                    self.lon_start,
                    self.lat_end,
                    self.lon_end,
                )
        self.cum_distances_m = cumulative_distances(self.waypoints)
        self.length_m = self.cum_distances_m[-1] if self.cum_distances_m else 0.0
        if not self.stations:
            self.stations = generate_stations(self.name, self.waypoints, self.cum_distances_m)

    def position_at(self, distance_m: float) -> tuple[float, float, float]:
        """Convenience: ``(lat, lon, bearing)`` at distance along route."""
        return position_at_distance(self.waypoints, self.cum_distances_m, distance_m)


# Real Kazakhstan railway routes — start/end are real cities, but the
# polylines between them are synthetic (see module docstring).
ROUTES: list[Route] = [
    Route("Almaty-Astana", 43.26, 76.95, 51.16, 71.47, electrified=True),
    Route("Astana-Petropavlovsk", 51.16, 71.47, 54.86, 69.14, electrified=False),
    Route("Astana-Ekibastuz", 51.16, 71.47, 51.72, 75.32, electrified=False),
    Route("Almaty-Shymkent", 43.26, 76.95, 42.34, 69.59, electrified=True),
    Route("Shymkent-Turkestan", 42.34, 69.59, 43.29, 68.27, electrified=False),
    Route("Ekibastuz-Pavlodar", 51.72, 75.32, 52.28, 76.97, electrified=False),
    Route("Aktobe-Atyrau", 50.28, 57.20, 47.12, 51.88, electrified=False),
    Route("Aktobe-Kostanay", 50.28, 57.20, 53.21, 63.62, electrified=False),
    Route("Almaty-Balkhash", 43.26, 76.95, 46.84, 74.98, electrified=False),
    Route("Astana-Kokshetau", 51.16, 71.47, 53.28, 69.39, electrified=False),
]


def get_route(name: str) -> Route | None:
    for r in ROUTES:
        if r.name == name:
            return r
    return None
